name: Metrics

on:
  schedule:
    - cron: "0 * * * *" # a cada 1 hora
  workflow_dispatch:      # permite rodar manualmente
  push:
    branches: ["main"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run GitHub Metrics
        uses: lowlighter/metrics@v2.2.0 # substitua pela última versão disponível
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_topics: yes
          plugin_stars: yes
          filename: github-metrics.svg

      - name: Upload Metrics SVG
        uses: actions/upload-artifact@v4
        with:
          name: github-metrics-svg
          path: github-metrics.svg
