name: Metrics
on:
  schedule: [{cron: "0 * * * *"}] # a cada 1 hora
  workflow_dispatch:              # permite rodar manualmente
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
