name: Metrics
on:
  schedule: [{cron: "0 * * * *"}] # Atualiza a cada 1 hora
  workflow_dispatch: # Permite rodar manualmente
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_topics: yes
          plugin_stars: yes
