name: Metrics

on:
  schedule: [{cron: "0 * * * *"}] # a cada 1 hora
  workflow_dispatch:              # permite rodar manualmente
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Configurações
          base: header, activity, community, repositories, metadata
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_topics: yes
          plugin_stars: yes
          filename: github-metrics.svg
